### ISSUE TITLE
Add links to view structural metadata artefacts

### ISSUE THREAD

**Issue by dbarr99** [OECDSTD/sdmx-matrix-generator#46]
For these artefacts which are required in the generator:
- Category scheme
- Agency scheme

This could be done by having a separate link to the "main registry", and having fields with the agency scheme and category scheme. Consider:
- The goal of discovering the schemes without knowing the names. Query them all by:
https://registry.sdmx.org/ws/public/sdmxapi/rest/agencyscheme/all/all/latest/?format=sdmx-2.1&detail=full&references=none

- Query a specific scheme by:
https://registry.sdmx.org/ws/public/sdmxapi/rest/agencyscheme/all/AGENCIES/latest/?format=sdmx-2.1&detail=full&references=none

**Comment by j3an-baptiste** [comment]
Migrated to GitLab https://gitlab.com/sis-cc/sdmx-matrix-generator/-/issues/3
