### ISSUE TITLE
Pre-fill feature for several DSDs doesn't load all DSD details

### ISSUE THREAD

**Issue by anastassias** [OECDSTD/sdmx-matrix-generator#50]
When pre-filling DSD matrix with Dataflows that use different DSDs defined in the file, not all DSD details are loaded correctly. There is empty space beween the first and the second DSD and second DSD name is missing. When generating SDMX out of such pre-filled matrix, the SDMX-ML is not valid.

[Multiple DSDs in one file.zip](https://github.com/OECDSTD/sdmx-matrix-generator/files/4298072/Multiple.DSDs.in.one.file.zip)

**Comment by dbarr99** [comment]
Fixed
