### ISSUE TITLE
XML generation fails when some dataflow categorisations are empty

### ISSUE THREAD

**Issue by anastassias** [OECDSTD/sdmx-matrix-generator#51]
When category scheme agency, ID version and category are missing for some of the DFs in the file (meaning that some DFs shouldn't be categorised), the XML generation fails with the error: Missing details in Categorisations, some not generated (file is not generated at all).

I think these DFs should be just skipped and the file should be generated.

[XML Generator of PPI V1.0.xlsm.zip](https://github.com/OECDSTD/sdmx-matrix-generator/files/4376267/XML.Generator.of.PPI.V1.0.xlsm.zip)

**Comment by dbarr99** [comment]
Fixed
