### ISSUE TITLE
Locale language setting in Excel different from English #53

### ISSUE THREAD

**Issue by pb20389** [OECDSTD/sdmx-matrix-generator#60]
Thanks for the adjustments of the issue #53, 

I just tested the fixes for the "isFinal" value, but it does not quite work for me yet. 

There are still some small VBA-Code corrections to be made regarding the "isFinal", 
see the Word document in the attached Zip-File.

Then it should work.

See also the corrected Excel file which I included in the Zip-File.

Thanks a lot

Markus P.

[Corrected_Test_File_and_Instructions.zip](https://github.com/OECDSTD/sdmx-matrix-generator/files/4884686/Corrected_Test_File_and_Instructions.zip)

_Originally posted by @pb20389 in https://github.com/OECDSTD/sdmx-matrix-generator/issues/53#issuecomment-654811484_

**Comment by dbarr99** [comment]
Hi Markus,
I'm just about to post a new version of this tool and I'd like to fix this issue. May I clarify with you that the only change required to the code is this:
- Change all "isFinal" properties from Boolean to String

The list for drpBoolean is already TRUE, FALSE.

Best, David

**Comment by pb20389** [comment]
Hi David,

yes, that is correct for this issue.

Thank you 

Markus

**Comment by dbarr99** [comment]
Great, thanks. I made the fix and I'm testing it now with users that experienced the issue, and I integrated your other fix. Hopefully I'll post the version in the next few days.

**Comment by dbarr99** [comment]
Fixed this in 27/11/2020 release, thanks Markus!
