### ISSUE TITLE
Prefill from Rest API goes in error with Excel language settings "German"

### ISSUE THREAD

**Issue by pb20389** [OECDSTD/sdmx-matrix-generator#66]
If the DSD-Matrix Generator is executed with Excel language settings "**German=Deutsch**",
the execution of the function "**_Prefill from REST API_**" terminate with a runtime error 

450 = "_Wrong number of arguments or invalid property assignment on vba_" 

in the macro "**ModGenerate_SDMXML**" of the sub-procedure "**PopulateMatrixConceptsAndCLsFromCS**" 
at statement: 

nextBlank.Style = "Input”

The reason is that in Excel with German language settings the cell formatting template is called "**Eingabe**" and **not “Input**”.

I tried to set the statement to **nextBlank.Style = “Eingabe”** and then the “Prefill from REST API” is working for Excel with German-Language settings.

Best regards
MP

**Runtime-Error: 450:**
![Runtime_ERROR](https://user-images.githubusercontent.com/64268319/95869901-2c8d0300-0d6c-11eb-9804-0a9cb73c251f.png)

**Temporary Workaround:**
![Temporary_Workaround](https://user-images.githubusercontent.com/64268319/95869917-30208a00-0d6c-11eb-9a64-3649607916ac.png)

**Comment by dbarr99** [comment]
Thanks so much for this fix, Markus. I'll be sure to include it in the next release.

All the best, David

**Comment by dbarr99** [comment]
Fixed this in 27/11/2020 release, thanks Markus!
