### ISSUE TITLE
Dimension with role D(Frequency) is skipped when generating attachment relationship for time-series attribute

### ISSUE THREAD

**Issue by anastassias** [OECDSTD/sdmx-matrix-generator#68]
This issue occurs when "Dimension (Frequency)" role is chosen for dimension FREQ on the Concept Scheme sheet. In this case the time-series attribute relation in DSD will contain all dimensions except FREQ.
When ordinary "Dimension" role is used for FREQ, it is correctly taken into account when time series attribute relationship is generated.
[V3_EMPTY - Generic DSD Matrix SDMXML generator.zip](https://github.com/OECDSTD/sdmx-matrix-generator/files/5372064/V3_EMPTY.-.Generic.DSD.Matrix.SDMXML.generator.zip)

**Comment by dbarr99** [comment]
Fixed this in 27/11/2020 release
